### PR TITLE
Passing message to execute functions, changing icons and removing unnecessary headings

### PR DESCRIPTION
**Pull request by kabir-afk**
### Changes Made:

1. [76594aa](76594aa87576a0151755fa1ccfc8bde167413086) - Removed unnecessary headings
2. [72bff78](72bff78aa75224909ee1ce969d1bab9fc9d66ba4) - Updated CSS background images for navigation icons
3. [fec65d9](fec65d953efbcaad335d0b887080ab3dff11b9fd) - Added messages for functions relying on "backgroundPage"
4. [2add156](2add15669f911f5593e24a7847ca293333eedbec) - Refactored code based on new messages

### Description

While first 2 changes are minor , I would like to elaborate on the 3rd and 4th ones. Apparently we borrowed some functions from `background-script.js` , for example:- `backgroundPage.normalize` or `backgroundPage.checkActiveTabInjections`. But in Chrome MV3 we cant do such things. In order to mimic this behavior I came across various methods which I am going to discuss down below:-

- **Sending messages from content/popup to sw,js :** This is the approach currently in use , messages are sent from popup script and based on the message ,that respective function is carried out. In case of `background-script,js`, it is necessary to return after calling the function otherwise it doesn't work. While it works and looks ok , it isn't necessary the best approach since there are segments we cant always send messages for , like [here](https://github.com/lingua-libre/SignIt/blob/de40f0737b8b00098976c890cbfb3ad1cfb7ab50/popup/popup.js#L325-L340). 

Different browsers have namespace differences as well as different API function coverage..for example while in FF we can still make use of `_backgroundPage.getBackground()`, but we can't do it in Chrome because of the MV3 limitations. And browser type checking for different browsers isn't certainly scalable or efficient. This is also one of the reasons why above approach is better as it is pretty universal to all the browsers and doesn't require much change.

- **Using a shared common-functions file :** While it seems to be the ideal approach and allows to produce the same results , it threw error `checkActiveTabInjections is not defined`. 
Error

If we can make this work , then it'll be better overall , no more unnecessary messages and compatible across both `sw.js` and `background-script.js`. We won't need to change the way messages are received as there will be no messages to begin with. It will also not hinder with the problem mentioned above. Maybe I might have done something wrong but again we should keep trying.

- **Storing functions inside local storage:** While we cant do that , it is technically possible by making it a string (like an actual string and not using `JSON.stringify()`)and storing its arguments inside an array , then rebuilding it by parsing it and passing the items inside the functions. Seems a bit bizarre and makes for unnecessary code but if it were to happen , functions would be available wherever needed as they are in local storage.

### CODE REVIEW

**Review by hugolpz — APPROVED** [review]
Move to i18n, all good.

**Review by hugolpz — APPROVED** [review]
Move to externalize icons, all good.

**Comment by hugolpz** [comment]
> Btw , translate wikibot hasn't changed the `pnb.json` file to `urdu.json`...should I add that ?

Nope, i asked Translatewiki, they will guide us.

**Review by hugolpz — APPROVED** [review]
Approved but I'm not sure I understand it all.
Namely :
- some code is commented, I don't see replacement (201-210)

I liked L109-116 : send message to sw, run function.

**Comment by kabir-afk** [comment]
Well L201-210 relied on `signlanguages` which further relied on the `getSignLanguagesWithVideos` function, which has an API endpoint issue. So I commented it out in order to proceed forward, otherwise it would have been stuck there the whole time

**Pull request merged**
