### PR TITLE
Update en.json

### LINKED ISSUE #22: Translation issue with message Wikimedia:Signit-si-overlay-coreContent-right-error/hi
URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=signit-si-overlay-coreContent-right-error&group=signit&language=hi

`No defition found.` should be `No defintion found.`

### PR DESCRIPTION
**Pull request by jhsoby**
Fix some grammar/spelling:
* Change "Medias" to "Media" (media is already plural in English)
* Change "interface's language" to "interface language"
* Change "desactives" to "deactivates"
* Change "integration into Wikipedia" to "integration with Wikipedia"
* Change "enlighten" to "highlight"
* Change "defition" to "definition" (this fixes #22)

### CODE REVIEW

**Comment by jhsoby** [comment]
Also, I don't really understand the meaning of "Double play normal / slow" – does it mean you speed up or slow down the video? That needs a change too, but I'm not sure what it should be changed to.

**Comment by hugolpz** [comment]
@jhsoby "Double play normal / slow" : SignIt display a video of sign language. It's often too rapid for most people. So we have an option to play the video twice, first at normal speed (x1), then at half speed (x0.5). So we have double play, at normal and then at slow (half speed).

**Review by hugolpz — APPROVED** [review]
Thank @jhsoby

**Comment by jhsoby** [comment]
Okay, that's what I thought. If it is just one button to change to faster/slower, I would suggest just labeling it "Play faster/slower".

**Comment by hugolpz** [comment]
It's not a switch, moving from normal to slow. It's a switch between 
1. Normal
2. Normal AND THEN slow.
So there is a double play.

**Comment by jhsoby** [comment]
Ah, okay. Then I suggest something like "Play at normal speed, then at slow speed" if that's not too long.

**Comment by hugolpz** [comment]
Ok, fixed. f862077a14f375d4bc9cb60386ccbf6bc00eb26a
Thanks again. It's great to have this help.

**Pull request merged**
