### PR TITLE
Testing `browser.i18n` API

### PR DESCRIPTION
**Pull request by kabir-afk**
## Changes

- [4af82b](https://github.com/lingua-libre/SignIt/commit/4af82b64dc36049818bb0d02e17cf84615d7a6f2) - added `target='_blank'` so that  speaker url opens in new tab
- [d29827](https://github.com/lingua-libre/SignIt/commit/d298273d0d3bb8f76a18d8a4bd60c76caa92246d) - replacing `extensionName` in 3197d1 to `si_addon_title`
- [6bc7b9](https://github.com/lingua-libre/SignIt/commit/6bc7b9197a0f5e88053f7588963d7e73e398b885) - replaced `banana.i18n` with `browser.i18n.getMessage()` as addressed in #86 
## Result 

| Scope | Chrome | Firefox |
| --- | --- | --- |
| Popup > Settings  | ✔ | ✔ |
| Popup > Browse > video gallery | ✔ | ✔ |
| Content script > modal > video gallery  | ✔ | ✔ |

**NOTE:** When talking about settings , `changeUiLanguage` function is not being talked about

### CODE REVIEW

**Review by hugolpz — CHANGES_REQUESTED** [review]
This wont work since these two messages are not in `./i18n/*.json` files. 
Use messages which exist in  `./i18n/*.json` files :
- `"name": "__MSG_si_addon_title__"`
- "description": *nothing for now, I will handle this later*.

**Review by hugolpz — APPROVED** [review]
```diff
- banana.i18n("si-popup-settings-history")
+ browser.i18n.getMessage("si_popup_settings_history")
```
There we go !!!  😈 🎉

**Review by hugolpz — APPROVED** [review]
__MSG* : thank you !

**Comment by kabir-afk** [comment]
> @kabir-afk : The manifest.json change wont work since these two messages do not exist in `./i18n/*.json` files. Use messages which exist in `./i18n/*.json` files :
> 
> * `"name": "__MSG_si_addon_title__"`
> * "description": _nothing for now, I will handle this later_.

I have addressed the same in [d29827](https://github.com/lingua-libre/SignIt/commit/d298273d0d3bb8f76a18d8a4bd60c76caa92246d) as well as mentioned in the PR above.

**Pull request merged**
