### PR TITLE
Multiple Code Enhancements

### PR DESCRIPTION
**Pull request by kabir-afk**
### 5th June 
   - [e9c8dd](https://github.com/lingua-libre/SignIt/commit/e9c8dd00c28db7d12b0ebe5fcb2e66b3c26e6482) - Replaced `return` with `sendResponse` function while sending records upon receiving the message `signit.getfiles`.
   - [c83333](https://github.com/lingua-libre/SignIt/commit/c8333373699dddafbd6e0413050326c91b5e7cd0) - As the commit message says, doing this enables the search functionality.
   - [7216bf](https://github.com/lingua-libre/SignIt/commit/7216bfa568707bda5f724432ebc73ee5c06fd69f) - Updated browser to chrome API for chrome to recognize the changes. FYI : Chrome namespace is recognized by Firefox as well.
   - [c01b13](https://github.com/lingua-libre/SignIt/commit/c01b13390e8e6b3f842aac39b6834729e27c0aa0) - Refined string split. Similar to what we did [here](https://github.com/lingua-libre/SignIt/pull/72/commits/49ec9a72da558be566d2b742029fe6d8f2104a1c) in `background-script.js`.
   - [2a8bb6](https://github.com/lingua-libre/SignIt/commit/2a8bb61f17352ec3b8c5d89c147a2ec1e642ff2e) - `SearchWidget` placeholder relied on i18n to reflect the number of records ,sign language videos are present for. So updated i18n to reflect that.
  
### 7th June
  - As mentioned in #82 , changed the CSS to use Unicode references as they work in both popup and content scripts , don't violate any CSP and work across all browsers. They also adapt to UI library's CSS.

### CODE REVIEW

**Review by hugolpz — APPROVED** [review]

**Comment by hugolpz** [comment]
There are a lot of tiny bits so I will only review those which puzzle me a bit, with ideas when I have.
- Q1: 7216bfa568707bda5f724432ebc73ee5c06fd69f : We also have a generic local `browser.` as a switch between web extension `chrome.` on chrome-based and web extension `browser.` on Firefox. See https://github.com/lingua-libre/SignIt/blob/master/popup/popup.js#L4 . If Firefox recognizes `chrome.`, let's ditch out that switch and go for `chrome.` alone, no ?
- Q2: 2a8bb61f17352ec3b8c5d89c147a2ec1e642ff2e Idea : make it more generic with array for when there are $1, $2, $3, $n.
- Q3: 67a193bd1ea0ed037437ee72f1ff89db7c0dfa29 place the unicode character directly in HTML ?

**Comment by hugolpz** [comment]
@kabir-afk , ok for Q1, Q2, Q3.
Please note that oojs will / should be ditched out somedays. Maybe in coming weeks if we have time.

**Comment by kabir-afk** [comment]
What will we be replacing it with ?

**Comment by hugolpz** [comment]
@kabir-afk Vanilla js / html / css.

**Pull request merged**
