### PR TITLE
changed the logo and added respective dimension

### LINKED ISSUE #39: Realign visual branding
Move toward a more Sign Languages specific visual branding.

### Colors
- [x] grey `#474847` or `#484848` (or variants) https://github.com/lingua-libre/SignIt/commit/17a39d2b91d873ab9e7fa0acbe89f8056d89a6f9
- [x] green #00a99d https://github.com/lingua-libre/SignIt/commit/a1e40d0c4fc4316eea3f4b5af6d433af17e1ee58#diff-5f677133bd3f5a4dddc8497184199679c2c3b434018feaad5325405970cc3dde
- [x] NOT TO USE. blue #36c

#### Phase 1
- [x] Decide a base color : KEEP GREEN
- [x] Create new logo with hands https://commons.wikimedia.org/wiki/File:Lingualibre_SignIt-logo.svg
- [x] Adapt new logo with right color

#### Phase 2
- [x] Integrate new logo to repository https://github.com/lingua-libre/SignIt/tree/master/icons
- [x] regenerate derivative icons https://github.com/lingua-libre/SignIt/tree/master/icons
- [x] commit to repository
- [x] release on github https://github.com/lingua-libre/SignIt/releases 1.0.19

#### Phase 3
- [ ] recreate documentation screenshots https://github.com/lingua-libre/SignIt/tree/master/doc
- [ ] update commons screenshots https://commons.wikimedia.org/wiki/Category:Lingua_Libre_SignIt
  - [ ] meta https://meta.wikimedia.org/wiki/Lingua_Libre/SignIt
  - [ ] wikidata https://www.wikidata.org/wiki/Q113354157

#### Phase4
- [ ] redeploy on firefox addon store https://addons.mozilla.org/en-US/firefox/addon/lingua-libre-signit/

### PR DESCRIPTION
**Pull request by saltykheera**
fixes #39

### CODE REVIEW

**Comment by tatayabicchu** [comment]
all logo preview

**Comment by saltykheera** [comment]
No worries! GitHub newbie here. i didn't knew Issue solved already.

**Comment by hugolpz** [comment]
@saltykheerahello,
Nice to see your pushes. I must admit I'm also learning github and Pull Request management here, so we  both need to self train further and progress. 😵‍💫 😍 
❎  Right now we have three "changes" (icons, video toggle, syntax normalization) within 2 commits, within one pull request.
✅  Since there are 3 changes, best is to have 3 commits.
Since we have 2 features, best is to have two PR, one for each feature.
I believe you need to do one fork and pull request for each new feature proposal.
It is important to separate your commit with syntax normalization from the commit with actual code changes so the later is easy to review by your teammate. 👍🏼 
I believe you need to do one fork and pull request for each new feature proposal.

Can you do another fork and Pull request with 2 commits, one commit for your video toggle changes, one commit for your syntax normalization. So we can simply discard this PR #41 which starts too be confusing. (and I don't know how to clean it up.)

Allow me to also cc @Poslovitch who is a more solid developer. He is focus on other projects and rarely passing by tho.

It's pretty cool to see your video toggle idea & implementation coming to life. 😍

**Comment by hugolpz** [comment]
@saltykheera , I would like to keep some of your change but I don't know how to pick the code improvements and discard the logos replacements. If you known how to filter from an existing PR, let me know. I then give you access to lead this PR.

**Comment by hugolpz** [comment]
Hello @saltykheera ,
@ayoubolk assisted me to do a `git cherry-pick [your JS commit]` so I merged the js code without merging the logos. We are good ! Thank you Ayoubolk and Saltykheera !

**Pull request merged**
